=== KimPiks/BeStrong---Website-Layout/xml/dtd.dtd
<!ELEMENT site (training_plans, exercises, diet)>
  <!ELEMENT training_plans (training_plan+)>
    <!ELEMENT training_plan (day+)>
      <!ELEMENT day (body_part*)>
        
  <!ELEMENT exercises (exercise+)>
    <!ELEMENT exercise (name, description, link*, image*, engagement, equipment_needed, rep_ranges)>
      <!ELEMENT name (#PCDATA)>
      <!ELEMENT description (#PCDATA | link)*>
      <!ELEMENT link (#PCDATA)>
      <!ELEMENT image (#PCDATA)>
      <!ELEMENT engagement (body_part+)>
      <!ELEMENT equipment_needed (equipment+)>
        <!ELEMENT equipment (#PCDATA)>
      <!ELEMENT rep_ranges (#PCDATA)>
  <!ELEMENT diet (macro_list)>
    <!ELEMENT macro_list (macro_element+)>
      <!ELEMENT macro_element (#PCDATA)>

<!ELEMENT body_part (#PCDATA)>

<!ATTLIST training_plan plan_type CDATA #REQUIRED>
<!ATTLIST day n CDATA #REQUIRED>
<!ATTLIST day rest_day (true | false) "false">
<!ATTLIST exercise risky (low | medium | high) #REQUIRED>
<!ATTLIST link url CDATA #REQUIRED>
<!ATTLIST image url CDATA #REQUIRED>
<!ATTLIST equipment_needed optional (true | false) "false">
<!ATTLIST macro_element element (Białko | Węglowodany | Tłuszcze) #REQUIRED>
<!ATTLIST macro_element min_amount CDATA #REQUIRED>
<!ATTLIST macro_element max_amount CDATA #REQUIRED>

=== KimPiks/BeStrong---Website-Layout/xml/xml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE site SYSTEM "dtd.dtd"> -->

<site xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <training_plans>
    <training_plan plan_type="FullBodyWorkout">
      <day n="1" rest_day="false">
        <body_part>Chest</body_part>
        <body_part>Biceps</body_part>
        <body_part>Triceps</body_part>
        <body_part>Shoulders</body_part>
        <body_part>Back</body_part>
        <body_part>Legs</body_part>
      </day>
      <day n="2" rest_day="true"></day>
      <day n="3" rest_day="false">
        <body_part>Chest</body_part>
        <body_part>Biceps</body_part>
        <body_part>Triceps</body_part>
        <body_part>Shoulders</body_part>
        <body_part>Back</body_part>
        <body_part>Legs</body_part>
      </day>
      <day n="4" rest_day="true"></day>
      <day n="5" rest_day="false">
        <body_part>Chest</body_part>
        <body_part>Biceps</body_part>
        <body_part>Triceps</body_part>
        <body_part>Shoulders</body_part>
        <body_part>Back</body_part>
        <body_part>Legs</body_part>
      </day>
      <day n="6" rest_day="true"></day>
      <day n="7" rest_day="true"></day>
    </training_plan>

    <training_plan plan_type="Split">
      <day n="1" rest_day="false">
        <body_part>Chest</body_part>
        <body_part>Triceps</body_part>
      </day>
      <day n="2" rest_day="false">
        <body_part>Biceps</body_part>
        <body_part>Back</body_part>
      </day>
      <day n="3" rest_day="false">
        <body_part>Shoulders</body_part>
        <body_part>Legs</body_part>
      </day>
      <day n="4" rest_day="false">
        <body_part>Chest</body_part>
        <body_part>Triceps</body_part>
      </day>
      <day n="5" rest_day="false">
        <body_part>Biceps</body_part>
        <body_part>Back</body_part>
      </day>
      <day n="6" rest_day="false">
        <body_part>Shoulders</body_part>
        <body_part>Legs</body_part>
      </day>
      <day n="7" rest_day="true"></day>
    </training_plan>
  </training_plans>

  <exercises>
    <exercise risky="medium">
      <name>Bench Press</name>
      <description>
        Barbell press on a horizontal bench
        <link url="https://www.budujmase.pl/atlas/klatka-piersiowa/wyciskanie-sztangi-na-lawce-poziomej.html"></link>
      </description>
      <image url="https://caliberstrong.com/wp-content/uploads/2020/04/how-to-bench-press.jpg"></image>
      <engagement>
        <body_part>Chest</body_part>
      </engagement>
      <equipment_needed optional="true">
        <equipment>Bar</equipment>
        <equipment>Dumbbells</equipment>
      </equipment_needed>
      <rep_ranges>6 8 12 15</rep_ranges>
    </exercise>
    <exercise risky="high">
      <name>Deadlift</name>
      <description>
        An exercise involving many parts of the body
      </description>
      <link url="https://www.budujmase.pl/atlas/plecy/martwy-ciag.html"></link>
      <image url="https://krosfitsports.com/storage/app/public/post/JvS9VgevHlOmBj9jYPDYXCz15bHpQg86uznC4IGj.jpeg"></image>
      <engagement>
        <body_part>Back</body_part>
        <body_part>Legs</body_part>
      </engagement>
      <equipment_needed optional="true">
        <equipment>Bar</equipment>
        <equipment>Dumbbells</equipment>
      </equipment_needed>
      <rep_ranges>8 12 15</rep_ranges>
    </exercise>
    <exercise risky="low">
      <name>Military Press</name>
      <description>
        Pushing the barbell overhead
      </description>
      <link url="https://en.wikipedia.org/wiki/Overhead_press"></link>
      <link url="https://www.budujmase.pl/atlas/barki/military-press.html"></link>
      <image url="https://cdn-0.weighttraining.guide/wp-content/uploads/2022/04/Standing-wide-grip-barbell-overhead-press.png"></image>
      <image url="https://en.wikipedia.org/wiki/File:Seated-military-shoulder-press-1.png"></image>
      <engagement>
        <body_part>Shoulders</body_part>
      </engagement>
      <equipment_needed optional="false">
        <equipment>Bar</equipment>
      </equipment_needed>
      <rep_ranges>6 8 10 12 15</rep_ranges>
    </exercise>
  </exercises>

  <diet>
    <macro_list>
      <macro_element element="Białko" min_amount="1.2" max_amount="1.8"></macro_element>
      <macro_element element="Węglowodany" min_amount="5" max_amount="7"></macro_element>
      <macro_element element="Tłuszcze" min_amount="1.8" max_amount="2.2"></macro_element>
    </macro_list>
  </diet>
</site>
